#define WINXP 1
#ifndef LOAD_LIBRARY_SEARCH_SYSTEM32
  #define LOAD_LIBRARY_SEARCH_DEFAULT_DIRS 0
  #define LOAD_LIBRARY_SEARCH_APPLICATION_DIR 0
  #define LOAD_LIBRARY_SEARCH_SYSTEM32 0
  #define LOAD_LIBRARY_SEARCH_USER_DIRS 0
  #define LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR 0
#endif
